name: "ai_power_demo"

services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # master key
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      # 文件服务器地址
      - FILE_CENTER_SERVICE_HOST=${FILE_CENTER_SERVICE_HOST}
      # 图片识别服务地址
      - PICTURE_RECOGNITION_SERVICE_HOST=${PICTURE_RECOGNITION_SERVICE_HOST}
      # 语音识别服务地址
      - AUDIO_RECOGNITION_SERVICE_HOST=${AUDIO_RECOGNITION_SERVICE_HOST}
      # maxkb服务地址
      - MAXKB_API_HOST=${MAXKB_API_HOST}
      # maxkb服务的apikey
      - MAXKB_API_KEY=${MAXKB_API_KEY}
      # action_cable允许的请求来源
      - ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=${ACTION_CABLE_ALLOWED_REQUEST_ORIGINS}
      # solid_queue是否作为puma的插件运行
      - SOLID_QUEUE_IN_PUMA=${SOLID_QUEUE_IN_PUMA}

    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-data:
